name: CD Pipeline

on:
  workflow_dispatch:   # Allows manual trigger
  push:
    branches:
      - dev   # d√©ploiement seulement quand tu push sur dev

jobs:

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.7
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve


  deploy:
  needs: terraform   # ‚Üê important !
  runs-on: ubuntu-latest
  environment: dev 

  env:
    AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --production

    - name: Build app (if needed)
      run: npm run build --if-present

    # üîë Authentification avec Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    # üöÄ D√©ploiement sur Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "webapp-Safenotes"
        package: .
